export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const EDIT_ACCOUNT = 'EDIT_ACCOUNT';
export const GET_ACCOUNTS = 'GET_ACCOUNTS';
export const GET_ACCOUNT_BY_ID = 'GET_ACCOUNT_BY_ID';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';